mex -v -largeArrayDims CXXFLAGS='$CXXFLAGS -std=c++17 -m64' ...
    -I"D:\william\codes\onnxruntime-win-x64-gpu-1.18.0\include" -I"C:\lib\vcpkg\installed\x64-windows\include"  ...
    -Iutils.h -Imex_api.h -Imacros.h -Iinference.h -Iholders.h ...
    -L"C:\lib\vcpkg\installed\x64-windows\lib" -L"D:\william\codes\onnxruntime-win-x64-gpu-1.18.0\lib" ...
    -lopencv_world4  -lonnxruntime -lonnxruntime_providers_cuda ...
    mex_depth_pro_onnx_infer.cpp ...
    utils.cpp inference.cpp mex_api.cpp
